### PR TITLE
Font updates, fix columns past 1080p

### PR DESCRIPTION
**Pull request by MasterDalK**

### CODE REVIEW

**Comment by unarist** [comment]
Why changed to non-UI Meiryo?

**Comment by MasterDalK** [comment]
On non-windows the font is not condensed, but still has extra letter-spacing from meiryo ui. With non-UI, it is more consistent across platforms without meiryo ui

**Comment by unarist** [comment]
Ah, I see...

I also had searched some coexistence way some days ago, but it seemed difficult with CSS only. Personally I like Meiryo UI version, but I agree with your decision.

**Comment by bit-map** [comment]
We're trying to unify and fix stuff before it gets added as an option to the site itself, so if you want to check out and comment on that discussion as well: https://github.com/kirakiratter/mastodon/pull/10

**Comment by unarist** [comment]
@bitmapchaos Yeah, I've understood this changes because I saw backgrounds of this on that thread.

**Comment by MasterDalK** [comment]
Resolves #36

**Pull request merged**
