### PR TITLE
Update README.md with proper Markdown style/English edits

### PR DESCRIPTION
**Pull request by lae**

### CODE REVIEW

**Comment by lae** [comment]
I'm rebasing this.

**Comment by MasterDalK** [comment]
Oh I already comitted it before I saw that comment and fixed it up to work with the JP inclusion...

**Comment by lae** [comment]
Oh, well, okay, I'll let you clean it up again? It doesn't look like it's committed.

**Comment by lae** [comment]
That block of Japanese should go before Installation, it's an introduction in Japanese

**Comment by MasterDalK** [comment]
Oh, woops.

**Pull request merged**
